apiVersion: v1
kind: Secret
metadata:
  name: librenms-admin-user
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
  email: dGVzdEBleGFtcGxlLmNvbQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-conf
  labels:
    app: librenms
data:
  config-interfaces-php: |
    <?php
    $config['bad_if_regexp'][] = '/^docker[-\w].*$/';
    $config['bad_if_regexp'][] = '/^lxcbr[0-9]+$/';
    $config['bad_if_regexp'][] = '/^veth.*$/';
    $config['bad_if_regexp'][] = '/^virbr.*$/';
    $config['bad_if_regexp'][] = '/^lo$/';
    $config['bad_if_regexp'][] = '/^macvtap.*$/';
    $config['bad_if_regexp'][] = '/gre.*$/';
    $config['bad_if_regexp'][] = '/tun[0-9]+$/';
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
  labels:
    app: librenms
data:
  config.php: |
    <?php

    $config['db_host'] = getenv('DB_HOST');
    $config['db_port'] = intval(getenv('DB_PORT') ?: 3306);
    $config['db_user'] = getenv('DB_USER');
    if (getenv('DB_PASS_FILE')) {
        $config['db_pass'] = trim(file_get_contents(getenv('DB_PASS_FILE')));
    } else {
        $config['db_pass'] = getenv('DB_PASSWORD');
    }
    $config['db_name'] = getenv('DB_NAME');
    $config['db']['extension'] = 'mysqli';

    $config['user'] = 'librenms';
    $config['base_url'] = getenv('BASE_URL');
    $config['snmp']['community'] = array("public");
    $config['auth_mechanism'] = "mysql";
    $config['rrd_purge'] = 0;
    $config['enable_billing'] = 1;
    $config['show_services'] = 1;
    $config['update'] = 0;

    $config['nagios_plugins']   = "/usr/lib/nagios/plugins";

    $config['rrdtool_version'] = '1.7.0';
    $config['rrdcached'] = getenv('RRDCACHED_CONNECT') ?: "unix:/var/run/rrdcached/rrdcached.sock";

    $config['memcached']['enable'] = filter_var(getenv('MEMCACHED_ENABLE'), FILTER_VALIDATE_BOOLEAN);
    $config['memcached']['host'] = getenv('MEMCACHED_HOST');
    $config['memcached']['port'] = intval(getenv('MEMCACHED_PORT') ?: 11211);
    $config['memcached']['ttl'] = 240;


    // include internal config

    $configFiles = glob(__DIR__ . '/conf.internal.d/*.php');
    natcasesort($configFiles);

    foreach ($configFiles as $file) {
            include $file;
    }

    // include custom config

    $configFiles = glob(__DIR__ . '/conf.d/*.php');
    natcasesort($configFiles);

    foreach ($configFiles as $file) {
            include $file;
    }
---

# for versions before 1.8.0 use apps/v1beta1
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: librenms
spec:
  selector:
    matchLabels:
      app: librenms
  serviceName: librenms
  replicas: 1
  template:
    metadata:
      labels:
        app: librenms
    spec:
      initContainers:
      - name: init-librenmsdb
        image: librenms/librenms
        env:
        - name: APP_KEY
          value: "base64:VYfuekU+TDQKmB7pSmkXMKe9YYjULP1rzA1Tdt23oew="
        - name: DB_HOST
          value: "mysql.default.svc.cluster.local"
        - name: DB_NAME
          value: "librenms"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "123456"
#        - name: BASE_URL
#          value: "http://10.17.12.103"
        - name: TZ
          value: "UTC"
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: librenms-admin-user
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms-admin-user
              key: password
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: librenms-admin-user
              key: email
        command:
        - su
        - "-p"
        - "librenms"
        - "-c"
        - "cd /opt/librenms && php /opt/librenms/build-base.php && php /opt/librenms/adduser.php ${USERNAME} ${PASSWORD} 10 ${EMAIL}"
      containers:
      - name: librenms
        image: librenms/librenms
        env:
        - name: APP_KEY
          value: "base64:VYfuekU+TDQKmB7pSmkXMKe9YYjULP1rzA1Tdt23oew="
        - name: DB_HOST
          value: "mysql.default.svc.cluster.local"
        - name: DB_NAME
          value: "librenms"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "123456"
#        - name: BASE_URL
#          value: "http://10.17.12.103"
        - name: TZ
          value: "UTC"
        ports:
        - name: librenms-http
          containerPort: 80
        # - name: librenms-https
          # containerPort: 443
        volumeMounts:
        - name: librenms-logs
          mountPath: /opt/librenms/logs
        - name: librenms-rrd
          mountPath: /opt/librenms/rrd
        # - name: libressl
          # mountPath: /etc/nginx/ssl
        - mountPath: /opt/librenms/conf.d
          name: librenms-conf
#        - name: dbconfig
#          mountPath: /opt/librenms/config.php.default
#          readOnly: true
#          subPath: config.php.default
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
#      - name: dbconfig
#        configMap:
#          name: php-dbconfig
      - name: librenms-conf
        configMap:
          name: librenms-conf
          items:
          - key: config-interfaces-php
            path: interfaces.php
  volumeClaimTemplates:
  - metadata:
      name: librenms-logs
    spec:
      accessModes: ["ReadWriteOnce"]
      #storageClassName: nfs-client
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: librenms-rrd
    spec:
      accessModes: ["ReadWriteOnce"]
      #storageClassName: nfs-client
      resources:
        requests:
          storage: 2Gi
  # - metadata:
      # name: libressl
    # spec:
      # accessModes: ["ReadWriteOnce"]
      # resources:
        # requests:
          # storage: 1Gi